'use client'; // Adicionado para permitir o uso do Navbar que tem lógica de cliente

import type { Metadata } from "next"; // Metadata pode ser removido se 'use client' for usado e não houver mais metadata estática
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/lib/client/components/Navbar"; // Importar o componente Navbar

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// A Metadata pode causar problemas com 'use client', considere remover ou usar uma alternativa
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar /> {/* Incluir o Navbar aqui */}
        {children}
      </body>
    </html>
  );
}
